export const playerData = { 
  players: [
    {playerID: 1, lastName:'Lloyd', firstName:'John'},
    {playerID: 2, lastName:'Berry', firstName:'Rei'},
    {playerID: 3, lastName:'Green', firstName:'Austin'},
    {playerID: 4, lastName:'Osmer', firstName:'Haley'},
    {playerID: 5, lastName:'Blair', firstName:'Tyler'},
    {playerID: 6, lastName:'Ice', firstName:'Gary'},
    {playerID: 101, lastName:'Ice', firstName:'Serina'},
    {playerID: 102, lastName:'Armstrong', firstName:'Andrew'},
    {playerID: 103, lastName:'Parker', firstName:'Steven'},
    {playerID: 104, lastName:'Avigliano', firstName:'Fabian'},
    {playerID: 105, lastName:'Kleingorge', firstName:'Cory'},
    {playerID: 106, lastName:'Devore', firstName:'Corey'},
    {playerID: 107, lastName:'Moody', firstName:'Sam'},
    {playerID: 108, lastName:'Casteel', firstName:'Scott'},
    {playerID: 109, lastName:'Browdy', firstName:'Kim'},
    {playerID: 110, lastName:'Pietri', firstName:'Christina'},
    {playerID: 111, lastName:'Baker', firstName:'Jeff'},
    {playerID: 112, lastName:'Samuelson', firstName:'Aren'},
    {playerID: 113, lastName:'Monsour', firstName:'Ethan'},
    {playerID: 114, lastName:'', firstName:'Anderson'},
    {playerID: 115, lastName:'Brown', firstName:'Caitlin'},
    {playerID: 116, lastName:'Ullery', firstName:'Chris'},
    {playerID: 117, lastName:'Watkins', firstName:'Alexander'},
    {playerID: 118, lastName:'Adkins', firstName:'Katie'},
    {playerID: 119, lastName:'Downy', firstName:'Katie'},
    {playerID: 120, lastName:'Quinones', firstName:'Sammie'},
    {playerID: 121, lastName:'Watkins', firstName:'Raya'},
    {playerID: 122, lastName:'Little', firstName:'Dakota'},
    {playerID: 123, lastName:'Eagle', firstName:'Molly'},
    {playerID: 124, lastName:'Koppenhofer', firstName:'Anna'},
    {playerID: 125, lastName:'Boatwright', firstName:'Tommie'},
    {playerID: 126, lastName:'Devore', firstName:'James'},
    {playerID: 127, lastName:'', firstName:'Joel'},
    {playerID: 128, lastName:'', firstName:'Ashlee'},
    {playerID: 129, lastName:'Bennet', firstName:'Jessie'},
    {playerID: 130, lastName:'Phillips', firstName:'Josh'},
    {playerID: 131, lastName:'', firstName:'Gregory'},
    {playerID: 132, lastName:'', firstName:'Chloe'},
    {playerID: 133, lastName:'Henderson', firstName:'Devan'},
    {playerID: 134, lastName:'Edwards', firstName:'Nathan'},
    {playerID: 135, lastName:'Magee', firstName:'James'},
    {playerID: 136, lastName:'Swope', firstName:'John'},
    {playerID: 137, lastName:'Martin', firstName:'Jason'},
    {playerID: 138, lastName:'Watson', firstName:'Scott'},
    {playerID: 139, lastName:'Holder', firstName:'Nick'},
    {playerID: 140, lastName:'Gossett', firstName:'Abigail'},
  ] 
}

export const eventData = {
  events: [
    {eventID: 101, eventName: 'Event 1'},
    {eventID: 102, eventName: 'Event 2'},
    {eventID: 103, eventName: 'Event 3'},
    {eventID: 104, eventName: 'Event 4'},
    {eventID: 105, eventName: 'Event 5'},
    {eventID: 106, eventName: 'Event 6'},
    {eventID: 201, eventName: 'Event 7'},
    {eventID: 202, eventName: 'Event 8'},
    {eventID: 203, eventName: 'Event 9'},
  ]
}

export const playerSkillData = {
  playerSkills: [
    {charID: 101, skillID: 101, rank: 1},
    {charID: 101, skillID: 101, rank: 1},
    {charID: 101, skillID: 101, rank: 1},
    {charID: 101, skillID: 101, rank: 1},
    {charID: 101, skillID: 101, rank: 1},
    {charID: 101, skillID: 101, rank: 1},
    {charID: 101, skillID: 101, rank: 1},
    {charID: 101, skillID: 101, rank: 1},
    {charID: 101, skillID: 101, rank: 1},
    {charID: 101, skillID: 101, rank: 1},
    {charID: 101, skillID: 101, rank: 1},
    {charID: 101, skillID: 101, rank: 1},
  ]
}

export const charData = {
  characters: [
    {charID: 101, playerID: 101, charName: 'Rudy', seasonPass: true, court: 'Feral', body: 15, xp: 110, cXp: 15, deaths: 0},
    {charID: 102, playerID: 102, charName: 'Moss', seasonPass: true, court: 'Feral', body: 15, xp: 110, cXp: 20, deaths: 0},
    {charID: 103, playerID: 105, charName: 'Silas', seasonPass: false, court: 'Courtless', body: 15, xp: 80, cXp: 18, deaths: 0},
    {charID: 104, playerID: 103, charName: 'Lance', seasonPass: true, court: 'Umbral', body: 15, xp: 110, cXp: 22, deaths: 0},
    {charID: 105, playerID: 107, charName: 'Dr Forrest', seasonPass: true, court: 'Umbral', body: 15, xp: 110, cXp: 22, deaths: 1},
    {charID: 106, playerID: 108, charName: 'Patches', seasonPass: false, court: 'Catalytic', body: 15, xp: 95, cXp: 16, deaths: 0},
    {charID: 107, playerID: 109, charName: 'PJ', seasonPass: true, court: 'Courtless', body: 15, xp: 110, cXp: 21, deaths: 0},
    {charID: 108, playerID: 112, charName: 'Tony', seasonPass: true, court: 'Courtless', body: 15, xp: 110, cXp: 23, deaths: 0},
    {charID: 109, playerID: 104, charName: 'Braum', seasonPass: true, court: 'Radiant', body: 15, xp: 110, cXp: 20, deaths: 0},
    {charID: 110, playerID: 106, charName: 'Dio', seasonPass: true, court: 'Radiant', body: 15, xp: 110, cXp: 21, deaths: 0},
  ]
}

export const skillData = {
  skills: [
{skillID: 100, skillCost: 8, skillDesc: 'Avoid an attack that you can see, coming from the front of you', skillName: 'Avoidance', skillRank: 1, skillType: 1, xpCost: 20},
{skillID: 101, skillCost: 0, skillDesc: 'Does increased damage from behind your target', skillName: 'Backstab', skillRank: 3, skillType: 1, xpCost: 5},
{skillID: 102, skillCost: 5, skillDesc: 'Disable a target limb for x seconds', skillName: 'Disable Limb', skillRank: 1, skillType: 1, xpCost: 15},
{skillID: 103, skillCost: 0, skillDesc: 'Allows you to carry a weapon in your off hand', skillName: 'Dual Wield', skillRank: 1, skillType: 1, xpCost: 10},
{skillID: 104, skillCost: 3, skillDesc: 'Gives you extra strength', skillName: 'Feat of Strength', skillRank: 1, skillType: 1, xpCost: 15},
{skillID: 105, skillCost: 3, skillDesc: 'Allows you to resist disarm', skillName: 'Firm Grip', skillRank: 1, skillType: 1, xpCost: 10},
{skillID: 106, skillCost: 0, skillDesc: 'If your unmodified armor cap is at least 13, damage you take to your armor does not overflow to your body. ', skillName: 'Heavy Armor Affinty', skillRank: 1, skillType: 1, xpCost: 10},
{skillID: 107, skillCost: 0, skillDesc: 'Increases max body by 5', skillName: 'Lesser Stamina', skillRank: 5, skillType: 1, xpCost: 5},
{skillID: 108, skillCost: 0, skillDesc: 'If your unmodified armor cap is at least 5, you can repair it back to 5 on a 60 second count', skillName: 'Light Armor Affinty', skillRank: 1, skillType: 1, xpCost: 10},
{skillID: 109, skillCost: 6, skillDesc: 'Add 10 damage to your next attack', skillName: 'Mortal Strike', skillRank: 2, skillType: 1, xpCost: 10},
{skillID: 110, skillCost: 0, skillDesc: 'Increases weapon damage', skillName: 'One Handed Prof', skillRank: 3, skillType: 1, xpCost: 10},
{skillID: 111, skillCost: 3, skillDesc: 'Blocks a numeric effect with your weapon', skillName: 'Parry', skillRank: 1, skillType: 1, xpCost: 10},
{skillID: 112, skillCost: 5, skillDesc: 'Stuns a target if you are holding a shield', skillName: 'Shield Bash', skillRank: 1, skillType: 1, xpCost: 15},
{skillID: 113, skillCost: 3, skillDesc: 'Blocks a status effect or a numeric effect ', skillName: 'Shield Guard', skillRank: 1, skillType: 1, xpCost: 10},
{skillID: 114, skillCost: 3, skillDesc: 'Allows you to resist the knockdown tagline', skillName: 'Steady Footing', skillRank: 1, skillType: 1, xpCost: 10},
{skillID: 115, skillCost: 2, skillDesc: 'Add sunder armor tagline to your next melee attack', skillName: 'Sunder Armor', skillRank: 1, skillType: 1, xpCost: 10},
{skillID: 116, skillCost: 0, skillDesc: 'Increases weapon damage', skillName: 'Two Handed Prof', skillRank: 5, skillType: 1, xpCost: 5},
{skillID: 117, skillCost: 6, skillDesc: 'Makes the "Avoidance" retort inert', skillName: 'Unavoidable', skillRank: 1, skillType: 1, xpCost: 20},
{skillID: 200, skillCost: 5, skillDesc: 'double damage', skillName: 'Aimed Shot', skillRank: 1, skillType: 2, xpCost: 15},
{skillID: 201, skillCost: 0, skillDesc: 'Increases damage done by handguns by 1', skillName: 'High Capacity Prof', skillRank: 3, skillType: 2, xpCost: 10},
{skillID: 202, skillCost: 0, skillDesc: 'Increases damage done by rifles by 3', skillName: 'Low Capacity Prof', skillRank: 3, skillType: 2, xpCost: 15},
{skillID: 203, skillCost: 2, skillDesc: 'May quietly shoot (magic, stfu)', skillName: 'Muffled Shot', skillRank: 1, skillType: 2, xpCost: 5},
{skillID: 204, skillCost: 5, skillDesc: 'Allows you to inflict the fear status effect to a target that is not in combat from behind.', skillName: 'Threaten', skillRank: 1, skillType: 2, xpCost: 15},
{skillID: 205, skillCost: 3, skillDesc: 'Quick disarm', skillName: 'Trick Shot', skillRank: 1, skillType: 2, xpCost: 10},
{skillID: 206, skillCost: 3, skillDesc: 'Repulse', skillName: 'Warning Shot', skillRank: 1, skillType: 2, xpCost: 10},
{skillID: 300, skillCost: 0, skillDesc: 'Gain 1 Radiant spell', skillName: 'Additional Radiant Spells', skillRank: 8, skillType: 3, xpCost: 10},
{skillID: 301, skillCost: 0, skillDesc: 'Add a socket of the buyers choice', skillName: 'Additional Socket', skillRank: 3, skillType: 3, xpCost: 10},
{skillID: 302, skillCost: 0, skillDesc: 'Starts with 1 Ira, 1 Acedia, 1 Varitia', skillName: 'Artificing', skillRank: 1, skillType: 3, xpCost: 15},
{skillID: 303, skillCost: 0, skillDesc: 'Gain 1 Shadow spell', skillName: 'Basic Shadow Spell', skillRank: 6, skillType: 3, xpCost: 10},
{skillID: 304, skillCost: 0, skillDesc: 'Gain 1 Complex Wild Magic Spell', skillName: 'Complex Wild Spell', skillRank: 5, skillType: 3, xpCost: 15},
{skillID: 305, skillCost: 0, skillDesc: '1/event/rank change socketed jewels outside of reset time with 5 minute RP', skillName: 'Emergency Re-Fit', skillRank: 2, skillType: 3, xpCost: 15},
{skillID: 306, skillCost: 0, skillDesc: 'Figure Out What The Gem Does Skill', skillName: 'Identify Gem', skillRank: 1, skillType: 3, xpCost: 5},
{skillID: 307, skillCost: 0, skillDesc: 'Increase Radiant Jolt damage by 1', skillName: 'Radiant Jolt Rank', skillRank: 2, skillType: 3, xpCost: 5},
{skillID: 308, skillCost: 0, skillDesc: 'Gain 3 Radiant spells', skillName: 'Radiant Magic', skillRank: 1, skillType: 3, xpCost: 20},
{skillID: 309, skillCost: 0, skillDesc: 'Gain 1 Sacrifice spell', skillName: 'Sacrifice Spell', skillRank: 2, skillType: 3, xpCost: 10},
{skillID: 310, skillCost: 0, skillDesc: 'Increase Shadow Jolt damage by 1', skillName: 'Shadow Jolt Rank', skillRank: 2, skillType: 3, xpCost: 10},
{skillID: 311, skillCost: 0, skillDesc: 'Gain 3 Shadow spells', skillName: 'Shadow Magic', skillRank: 1, skillType: 3, xpCost: 20},
{skillID: 312, skillCost: 0, skillDesc: 'Gain 1 Simple wild magic spell', skillName: 'Simple Wild Spell', skillRank: 2, skillType: 3, xpCost: 10},
{skillID: 313, skillCost: 0, skillDesc: 'Gain all cantrips, 2 simple spells', skillName: 'Wild Magic', skillRank: 1, skillType: 3, xpCost: 20},
{skillID: 400, skillCost: 1, skillDesc: 'Removes the unconcious status on a 10 count', skillName: 'Awaken', skillRank: 1, skillType: 4, xpCost: 5},
{skillID: 401, skillCost: 1, skillDesc: 'Removes the poison status on a 10 count', skillName: 'Detox', skillRank: 1, skillType: 4, xpCost: 5},
{skillID: 402, skillCost: 0, skillDesc: 'Know the status of a character', skillName: 'Diagnose', skillRank: 1, skillType: 4, xpCost: 5},
{skillID: 403, skillCost: 1, skillDesc: 'Removes the pain status on a 10 count', skillName: 'Ease Pain', skillRank: 1, skillType: 4, xpCost: 5},
{skillID: 404, skillCost: 0, skillDesc: 'Removes certain status effects on a 5 minute count', skillName: 'Field Surgery', skillRank: 1, skillType: 4, xpCost: 15},
{skillID: 405, skillCost: 0, skillDesc: 'Run with a body', skillName: 'Firemen Carry', skillRank: 1, skillType: 4, xpCost: 10},
{skillID: 406, skillCost: 2, skillDesc: 'Heal another character at a rate of 1 per 1 seconds, cannot be used on bleeding out character.', skillName: 'Mend Wounds', skillRank: 3, skillType: 4, xpCost: 10},
{skillID: 407, skillCost: 1, skillDesc: 'Removes the disabled limb status on 10 count', skillName: 'Reset Limb', skillRank: 1, skillType: 4, xpCost: 5},
{skillID: 408, skillCost: 1, skillDesc: 'Removes the waylaid status on a 10 count', skillName: 'Treat Waylaid', skillRank: 1, skillType: 4, xpCost: 5},
{skillID: 409, skillCost: 1, skillDesc: 'Add 5 minutes to a bleedout or death count', skillName: 'Triage', skillRank: 1, skillType: 4, xpCost: 10},
{skillID: 500, skillCost: 5, skillDesc: 'Allows you to inflict 25 body to a target that is not in combat from behind.', skillName: 'Ambush', skillRank: 1, skillType: 5, xpCost: 15},
{skillID: 501, skillCost: 1, skillDesc: 'Allows you to purge the captured status on a (10,5,1) minute count.', skillName: 'Escapism', skillRank: 3, skillType: 5, xpCost: 10},
{skillID: 502, skillCost: 2, skillDesc: 'Allows you to inflict the slow status effect to a target that is not in combat from behind.', skillName: 'Hamstring', skillRank: 1, skillType: 5, xpCost: 5},
{skillID: 503, skillCost: 3, skillDesc: 'Allows you to hide in the shadows', skillName: 'Hide', skillRank: 1, skillType: 5, xpCost: 15},
{skillID: 504, skillCost: 2, skillDesc: 'Allows you to pick a shit quality lock at 1 minute, good quality lock at 3 minutes, and great quality lock at 5 minutes', skillName: 'Pick Lock: Journeymen', skillRank: 1, skillType: 5, xpCost: 10},
{skillID: 505, skillCost: 0, skillDesc: 'Hide a hand sized item on your person, that cannot be found', skillName: 'Smuggle', skillRank: 3, skillType: 5, xpCost: 5},
{skillID: 506, skillCost: 5, skillDesc: 'Cause a target to go to waylaid status', skillName: 'Waylay', skillRank: 1, skillType: 5, xpCost: 15},
{skillID: 600, skillCost: 0, skillDesc: 'Allows you to sell items at the marketplace.', skillName: 'Barter', skillRank: 1, skillType: 6, xpCost: 15},
{skillID: 601, skillCost: 3, skillDesc: 'Allows you to resist a killing blow by begging for your life (can be used in bleed out)', skillName: 'Cower', skillRank: 1, skillType: 6, xpCost: 10},
{skillID: 602, skillCost: 3, skillDesc: '', skillName: 'Distraction', skillRank: 1, skillType: 6, xpCost: 10},
{skillID: 603, skillCost: 0, skillDesc: 'You make take back a social misstep. ', skillName: 'Etiquette', skillRank: 3, skillType: 6, xpCost: 10},
{skillID: 604, skillCost: 1, skillDesc: 'Allows you to forge documents', skillName: 'Forgery', skillRank: 10, skillType: 6, xpCost: 10},
{skillID: 605, skillCost: 0, skillDesc: 'After 10 minutes of role play, inflict a force truth on a captured target.', skillName: 'Interrogation', skillRank: 1, skillType: 6, xpCost: 10},
{skillID: 606, skillCost: 1, skillDesc: 'Allows you to resist detect lie', skillName: 'Silver Tongue', skillRank: 1, skillType: 6, xpCost: 20},
{skillID: 700, skillCost: 3, skillDesc: 'Allows you to resist blind', skillName: 'Blind Fighting', skillRank: 1, skillType: 7, xpCost: 10},
{skillID: 701, skillCost: 5, skillDesc: 'Combats tracking', skillName: 'Cover Tracks', skillRank: 1, skillType: 7, xpCost: 15},
{skillID: 702, skillCost: 3, skillDesc: 'Allows you to respond with the "feign dead" status if youve taken a knee', skillName: 'Feign Death', skillRank: 1, skillType: 7, xpCost: 10},
{skillID: 703, skillCost: 1, skillDesc: 'Allows you to track a target', skillName: 'Journeymen Tracking', skillRank: 3, skillType: 7, xpCost: 15},
{skillID: 704, skillCost: 1, skillDesc: 'Allows you to do various rope things, also allows you to inflict the captured status', skillName: 'Rope Use', skillRank: 1, skillType: 7, xpCost: 15},
{skillID: 705, skillCost: 0, skillDesc: 'You gain bonuses while on a ship', skillName: 'Sailing', skillRank: 1, skillType: 7, xpCost: 5},
{skillID: 706, skillCost: 0, skillDesc: 'Allows you to search a target for hidden items', skillName: 'Search Person', skillRank: 1, skillType: 7, xpCost: 5},
{skillID: 707, skillCost: 0, skillDesc: 'You gain bonuses while underground. ', skillName: 'Spelunker', skillRank: 1, skillType: 7, xpCost: 5},
{skillID: 708, skillCost: 0, skillDesc: 'You gain bonuses while in the wild', skillName: 'Survivalist', skillRank: 1, skillType: 7, xpCost: 5},
  ]
}