export const playerData = { 
  players: [
    {playerID: 1, lastName:'Lloyd', firstName:'John'},
    {playerID: 2, lastName:'Berry', firstName:'Rei'},
    {playerID: 3, lastName:'Green', firstName:'Austin'},
    {playerID: 4, lastName:'Osmer', firstName:'Haley'},
    {playerID: 5, lastName:'Blair', firstName:'Tyler'},
    {playerID: 6, lastName:'Ice', firstName:'Gary'},
    {playerID: 101, lastName:'Ice', firstName:'Serina'},
    {playerID: 102, lastName:'Armstrong', firstName:'Andrew'},
    {playerID: 103, lastName:'Parker', firstName:'Steven'},
    {playerID: 104, lastName:'Avigliano', firstName:'Fabian'},
    {playerID: 105, lastName:'Kleingorge', firstName:'Cory'},
    {playerID: 106, lastName:'Devore', firstName:'Corey'},
    {playerID: 107, lastName:'Moody', firstName:'Sam'},
    {playerID: 108, lastName:'Casteel', firstName:'Scott'},
    {playerID: 109, lastName:'Browdy', firstName:'Kim'},
    {playerID: 110, lastName:'Pietri', firstName:'Christina'},
    {playerID: 111, lastName:'Baker', firstName:'Jeff'},
    {playerID: 112, lastName:'Samuelson', firstName:'Aren'},
    {playerID: 113, lastName:'Monsour', firstName:'Ethan'},
    {playerID: 114, lastName:'', firstName:'Anderson'},
    {playerID: 115, lastName:'Brown', firstName:'Caitlin'},
    {playerID: 116, lastName:'Ullery', firstName:'Chris'},
    {playerID: 117, lastName:'Watkins', firstName:'Alexander'},
    {playerID: 118, lastName:'Adkins', firstName:'Katie'},
    {playerID: 119, lastName:'Downy', firstName:'Katie'},
    {playerID: 120, lastName:'Quinones', firstName:'Sammie'},
    {playerID: 121, lastName:'Watkins', firstName:'Raya'},
    {playerID: 122, lastName:'Little', firstName:'Dakota'},
    {playerID: 123, lastName:'Eagle', firstName:'Molly'},
    {playerID: 124, lastName:'Koppenhofer', firstName:'Anna'},
    {playerID: 125, lastName:'Boatwright', firstName:'Tommie'},
    {playerID: 126, lastName:'Devore', firstName:'James'},
    {playerID: 127, lastName:'', firstName:'Joel'},
    {playerID: 128, lastName:'', firstName:'Ashlee'},
    {playerID: 129, lastName:'Bennet', firstName:'Jessie'},
    {playerID: 130, lastName:'Phillips', firstName:'Josh'},
    {playerID: 131, lastName:'', firstName:'Gregory'},
    {playerID: 132, lastName:'', firstName:'Chloe'},
    {playerID: 133, lastName:'Henderson', firstName:'Devan'},
    {playerID: 134, lastName:'Edwards', firstName:'Nathan'},
    {playerID: 135, lastName:'Magee', firstName:'James'},
    {playerID: 136, lastName:'Swope', firstName:'John'},
    {playerID: 137, lastName:'Martin', firstName:'Jason'},
    {playerID: 138, lastName:'Watson', firstName:'Scott'},
    {playerID: 139, lastName:'Holder', firstName:'Nick'},
    {playerID: 140, lastName:'Gossett', firstName:'Abigail'},
  ] 
}

export const eventData = {
  events: [
    {eventID: 101, eventName: 'Event 1'},
    {eventID: 102, eventName: 'Event 2'},
    {eventID: 103, eventName: 'Event 3'},
    {eventID: 104, eventName: 'Event 4'},
    {eventID: 105, eventName: 'Event 5'},
    {eventID: 106, eventName: 'Event 6'},
    {eventID: 201, eventName: 'Event 7'},
    {eventID: 202, eventName: 'Event 8'},
    {eventID: 203, eventName: 'Event 9'},
  ]
}